apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: s3api
    - port: 9001
      targetPort: 9001
      name: admin
