apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  gatewayClassName: istio
  listeners:
    - name: mqtt-tls
      port: 8883
      protocol: TLS
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: Same
