apiVersion: v1
kind: Service
metadata:
  name: cratedb
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  selector:
    app: cratedb
  ports:
    - name: admin
      port: 4200
      targetPort: 4200
    - name: transport
      port: 4300
      targetPort: 4300
    - name: psql
      port: 5432
      targetPort: 5432
