{{- if .Values.secretData.rootCa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rootCa }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretData.rootCa | nindent 2 }}
{{- end }}
