apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-tenant-ca
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-tenant-ca
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: api
roleRef:
  kind: Role
  name: api-tenant-ca
  apiGroup: rbac.authorization.k8s.io
