apiVersion: v1
kind: Service
metadata:
  name: iot-agent
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  selector:
    app: iot-agent
  ports:
    - port: 4041
      targetPort: 4041
      name: north
    - port: 7896
      targetPort: 7896
      name: south
