apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.rabbitmq }}
