apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
