apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  labels:
    {{- include "gps-connector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: {{ .Values.images.alloy.repository }}:{{ .Values.images.alloy.tag }}
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: config
              mountPath: /etc/alloy/config.alloy
              subPath: config.alloy
      volumes:
        - name: config
          configMap:
            name: alloy-config
